### ISSUE TITLE
browserify?

### ISSUE THREAD

**Issue by tmcw** [veltman/wherewolf#26]
This would let you easily bundle the topojson dependency for browsers, automatically generate your AMD/UMD export, and avoid node/browser sniffing in the code. You could also cut some code by using modules that already implement some of this, like using point-in-polygon directly & [turf's modules](https://github.com/Turfjs/turf).

**Comment by veltman** [comment]
Makes sense, I'll take a crack at that. topojson would get double-included for some people in browser but seems tiny enough not to matter. I should probably also split coercing GeoJSON/TopoJSON into a proper FeatureCollection into a separate module.

**Comment by tmcw** [comment]
Closing as idle
